/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * main.c
 *
 *  Created on: Oct 21, 2024
 *      Author: Catherine Nader
 */

#include "standard_def.h"
#include "stdio.h"

#define RCC_Base 0x40021000
#define PORTA_Base 0x40010800

#define APB2ENR_R *(vuint32 *)(RCC_Base+0x18)
#define GPIOA_CRH_R *(vuint32 *)(PORTA_Base+0x04)
#define GPIOA_ODR_R *(vuint32 *)(PORTA_Base+0x0C)


int main()
{
	APB2ENR_R |= 1<<2;
	GPIOA_CRH_R &= 0xFF0FFFFF;
	GPIOA_CRH_R |= 0x00200000;

	while(1)
	{
	GPIOA_ODR_R |=1<<13;
	for(int i=0;i<5000;i++);
	GPIOA_ODR_R &= ~(1<<13);
	for(int i=0;i<5000;i++);

	}


return 0;
}
